-- ============================================================
-- Migration 039: Add rated_at column to review_requests
-- ============================================================
-- Tracks exactly when the customer submitted their rating on the
-- landing page. Previously, the feedback list was ordered by
-- created_at (when the request was generated by the cron) which
-- could push recently rated feedbacks down the list.
--
-- New ordering: COALESCE(rated_at, created_at) DESC so that:
--   - Feedbacks just rated jump to the top
--   - Pending (not yet rated) requests remain in creation order
-- ============================================================

ALTER TABLE `review_requests`
    ADD COLUMN `rated_at` DATETIME DEFAULT NULL AFTER `clicked_at`,
    ADD INDEX `idx_rated_at` (`rated_at`);

-- Backfill: for existing rated records, approximate rated_at with updated_at
-- (updated_at was touched when rating was saved). This is a best-effort
-- migration to avoid breaking the existing list ordering.
UPDATE `review_requests`
SET `rated_at` = `updated_at`
WHERE `rating` IS NOT NULL
  AND `rated_at` IS NULL;
